### ISSUE TITLE
Feature suggestion: embed inline images in single html file.

### ISSUE THREAD

**Issue by GlassGruber** [gonejack/email-to-html#2]
Hei there!
Would it be possible to add an option to have images saved as inline content to have a single html file? 
Ofc other non inline attachments would still be placed in `attachments` folder (like pdfs, other files or attached non inline images).

Thank you for your app, is very handy! 🎩👌

**Comment by gonejack** [comment]
Hi @GlassGruber 

Take a try with this https://github.com/gonejack/embed-html

**Comment by GlassGruber** [comment]
Interesting thank you!  
Unfortunately I can't tell why, but the program just stalls with nothing printed in the console. I've tried with verbose `-v` mode too, still nothing.  

As a side note the program stalls with no error message also when the command is called with no arguments. The help `-k` and `--about` commands are working.

**Comment by gonejack** [comment]
Hi, @GlassGruber 

I'm sorry, that I forgot this one is just experimental and I haven't finished at all.

Would like try to finish it when I got some time but shall not be happening in recent days.

**Comment by GlassGruber** [comment]
No worries at all! 

As a workaround, I've loaded the files in a local webserver (Caddy in this specific case), and used a very nice browser addon [SingleFile](https://github.com/gildas-lormeau/SingleFile/) to save the page as a single static file.

Looking forward to further developments of your apps, all the best!
